In [1]:
import numpy as np

In [2]:
#Get the common items between a and b

In [3]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

In [4]:
#From array a remove all items present in array b

In [5]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

# From 'a' remove all of 'b'
np.setdiff1d(a,b)

array([1, 2, 3, 4])

In [6]:
#Get the positions where elements of a and b match

In [7]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a == b)

(array([1, 3, 5, 7], dtype=int64),)

In [8]:
#Get all items between 5 and 10 from a.

In [9]:
a = np.arange(15)


index = np.where((a >= 5) & (a <= 10))
a[index]

array([ 5,  6,  7,  8,  9, 10])

In [10]:
# Convert the function maxx that works on two scalars, to work on two arrays.

In [12]:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

pair_max = np.vectorize(maxx, otypes=[float])

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max(a, b)

array([6., 7., 9., 8., 9., 7., 5.])

In [13]:
# Swap columns 1 and 2 in the array arr.

In [14]:
arr = np.arange(9).reshape(3,3)
arr

arr[:, [1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [15]:
#Swap rows 1 and 2 in the array arr:

In [16]:
arr = np.arange(9).reshape(3,3)


arr[[1,0,2], :]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [17]:
#Reverse the rows of a 2D array arr.

In [19]:
arr = np.arange(9).reshape(3,3)


arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [20]:
#Reverse the columns of a 2D array arr.

In [21]:
arr = np.arange(9).reshape(3,3)

arr[:, ::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [22]:
#Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.

In [23]:
arr = np.arange(9).reshape(3,3)

# Solution Method 1:
rand_arr = np.random.randint(low=5, high=10, size=(5,3)) + np.random.random((5,3))